export const genre = [
  "Mystery",
  "Fiction",
  "Fantasy",
  "Horror",
  "History",
  "Self-help",
  "Autobiography",
  "Biography",
  "Classic",
  "Dystopian",
  "Science Fiction",
  "Romance",
  "Adventure",
  "Coming-of-age",
  "Magical Realism",
  "Literary Fiction",
  "Historical Fiction",
  "Epic",
  "Mythology",
  "Poetry",
  "Philosophical Fiction",
  "Psychological Fiction",
  "Gothic",
  "Philosophical",
  "Satire",
  "Children's Literature",
  "Fable",
  "War",
  "Social Commentary",
  "Comedy",
  "Feminist Fiction",
  "Absurdist Fiction",
  "Existential",
  "Drama",
  "Young Adult",
  "Nature",
  "Post-Apocalyptic",
  "Historical",
  "Mythopoeia",
];
